-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 13:26:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto_individual_jg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_individual_jg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_individual_jg` DEFAULT CHARACTER SET utf8 ;
USE `proyecto_individual_jg` ;

-- -----------------------------------------------------
-- Table `proyecto_individual_jg`.`tipo_de_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_individual_jg`.`tipo_de_documento` (
  `cod_td` VARCHAR(5) NOT NULL,
  `desc_td` CHAR(35) NOT NULL,
  `estado_td` TINYINT NOT NULL,
  PRIMARY KEY (`cod_td`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_individual_jg`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_individual_jg`.`persona` (
  `id_persona` VARCHAR(13) NOT NULL,
  `p_nombre_p` CHAR(15) NOT NULL,
  `s_nombre_p` CHAR(15) NULL,
  `p_apellido_p` CHAR(15) NOT NULL,
  `s_apellido_p` CHAR(15) NULL,
  `estado_p` TINYINT NOT NULL,
  `tipo_de_documento_cod_td` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_persona`, `tipo_de_documento_cod_td`),
  INDEX `fk_persona_tipo_de_documento_idx` (`tipo_de_documento_cod_td` ASC) VISIBLE,
  CONSTRAINT `fk_persona_tipo_de_documento`
    FOREIGN KEY (`tipo_de_documento_cod_td`)
    REFERENCES `proyecto_individual_jg`.`tipo_de_documento` (`cod_td`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_individual_jg`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_individual_jg`.`cliente` (
  `pkfk_id_persona` VARCHAR(13) NOT NULL,
  `pkfk_cod_td` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`pkfk_id_persona`, `pkfk_cod_td`),
  INDEX `fk_cliente_persona1_idx` (`pkfk_id_persona` ASC, `pkfk_cod_td` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_persona1`
    FOREIGN KEY (`pkfk_id_persona` , `pkfk_cod_td`)
    REFERENCES `proyecto_individual_jg`.`persona` (`id_persona` , `tipo_de_documento_cod_td`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_individual_jg`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_individual_jg`.`producto` (
  `id_producto` INT(7) NOT NULL,
  `descripción_p` CHAR(21) NOT NULL,
  `estado_p` TINYINT NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_individual_jg`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_individual_jg`.`proveedor` (
  `pkfk_id_persona` VARCHAR(13) NOT NULL,
  `pkfk_tipo_de_documento_cod_td` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`pkfk_id_persona`, `pkfk_tipo_de_documento_cod_td`),
  INDEX `fk_proveedor_persona1_idx` (`pkfk_id_persona` ASC, `pkfk_tipo_de_documento_cod_td` ASC) VISIBLE,
  CONSTRAINT `fk_proveedor_persona1`
    FOREIGN KEY (`pkfk_id_persona` , `pkfk_tipo_de_documento_cod_td`)
    REFERENCES `proyecto_individual_jg`.`persona` (`id_persona` , `tipo_de_documento_cod_td`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_individual_jg`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_individual_jg`.`vendedor` (
  `salario_v` INT(7) NOT NULL,
  `pkfk_id_persona` VARCHAR(13) NOT NULL,
  `pkfk_tipo_de_documento_cod_td` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`pkfk_id_persona`, `pkfk_tipo_de_documento_cod_td`),
  INDEX `fk_vendedor_persona1_idx` (`pkfk_id_persona` ASC, `pkfk_tipo_de_documento_cod_td` ASC) VISIBLE,
  CONSTRAINT `fk_vendedor_persona1`
    FOREIGN KEY (`pkfk_id_persona` , `pkfk_tipo_de_documento_cod_td`)
    REFERENCES `proyecto_individual_jg`.`persona` (`id_persona` , `tipo_de_documento_cod_td`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_individual_jg`.`factura_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_individual_jg`.`factura_entrada` (
  `cod_factura_entrada` VARCHAR(4) NOT NULL,
  `fecha_entrada` DATETIME NOT NULL,
  `cantidad_entrada` INT(40) NOT NULL,
  `estado_entrada` TINYINT NOT NULL,
  `fk_pkfk_id_persona_en` VARCHAR(13) NOT NULL,
  `fk_pkfk_tipo_de_documento_cod_td_en` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`cod_factura_entrada`),
  INDEX `fk_factura_entrada_proveedor1_idx` (`fk_pkfk_id_persona_en` ASC, `fk_pkfk_tipo_de_documento_cod_td_en` ASC) VISIBLE,
  CONSTRAINT `fk_factura_entrada_proveedor1`
    FOREIGN KEY (`fk_pkfk_id_persona_en` , `fk_pkfk_tipo_de_documento_cod_td_en`)
    REFERENCES `proyecto_individual_jg`.`proveedor` (`pkfk_id_persona` , `pkfk_tipo_de_documento_cod_td`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_individual_jg`.`factura_salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_individual_jg`.`factura_salida` (
  `cod_factura_salida` VARCHAR(4) NOT NULL,
  `fecha_salida` DATETIME NOT NULL,
  `cantidad_salida` INT(20) NOT NULL,
  `estado_salida` TINYINT NOT NULL,
  `fk_pkfk_id_persona` VARCHAR(13) NOT NULL,
  `fk_pkfk_cod_td` VARCHAR(5) NOT NULL,
  `fk_pkfk_id_persona` VARCHAR(13) NOT NULL,
  `fk_pkfk_tipo_de_documento_cod_td_sa` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`cod_factura_salida`),
  INDEX `fk_factura_salida_cliente1_idx` (`fk_pkfk_id_persona` ASC, `fk_pkfk_cod_td` ASC) VISIBLE,
  INDEX `fk_factura_salida_vendedor1_idx` (`fk_pkfk_id_persona` ASC, `fk_pkfk_tipo_de_documento_cod_td_sa` ASC) VISIBLE,
  CONSTRAINT `fk_factura_salida_cliente1`
    FOREIGN KEY (`fk_pkfk_id_persona` , `fk_pkfk_cod_td`)
    REFERENCES `proyecto_individual_jg`.`cliente` (`pkfk_id_persona` , `pkfk_cod_td`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_salida_vendedor1`
    FOREIGN KEY (`fk_pkfk_id_persona` , `fk_pkfk_tipo_de_documento_cod_td_sa`)
    REFERENCES `proyecto_individual_jg`.`vendedor` (`pkfk_id_persona` , `pkfk_tipo_de_documento_cod_td`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_individual_jg`.`factura_entrada_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_individual_jg`.`factura_entrada_has_producto` (
  `pkfk_cod_factura_entrada` VARCHAR(4) NOT NULL,
  `pkfk_id_producto_en` INT(7) NOT NULL,
  PRIMARY KEY (`pkfk_cod_factura_entrada`, `pkfk_id_producto_en`),
  INDEX `fk_factura_entrada_has_producto_producto1_idx` (`pkfk_id_producto_en` ASC) VISIBLE,
  INDEX `fk_factura_entrada_has_producto_factura_entrada1_idx` (`pkfk_cod_factura_entrada` ASC) VISIBLE,
  CONSTRAINT `fk_factura_entrada_has_producto_factura_entrada1`
    FOREIGN KEY (`pkfk_cod_factura_entrada`)
    REFERENCES `proyecto_individual_jg`.`factura_entrada` (`cod_factura_entrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_entrada_has_producto_producto1`
    FOREIGN KEY (`pkfk_id_producto_en`)
    REFERENCES `proyecto_individual_jg`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_individual_jg`.`factura_salida_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_individual_jg`.`factura_salida_has_producto` (
  `pkfk_cod_factura_salida` VARCHAR(4) NOT NULL,
  `pkfk_id_producto_sa` INT(7) NOT NULL,
  PRIMARY KEY (`pkfk_cod_factura_salida`, `pkfk_id_producto_sa`),
  INDEX `fk_factura_salida_has_producto_producto1_idx` (`pkfk_id_producto_sa` ASC) VISIBLE,
  INDEX `fk_factura_salida_has_producto_factura_salida1_idx` (`pkfk_cod_factura_salida` ASC) VISIBLE,
  CONSTRAINT `fk_factura_salida_has_producto_factura_salida1`
    FOREIGN KEY (`pkfk_cod_factura_salida`)
    REFERENCES `proyecto_individual_jg`.`factura_salida` (`cod_factura_salida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_salida_has_producto_producto1`
    FOREIGN KEY (`pkfk_id_producto_sa`)
    REFERENCES `proyecto_individual_jg`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
